
/*
 * AUTOGENERATED FILE
 * Generator: JSAPI_IDL_compiler.py
 */

var DNSSECStatus = {
    INSECURE: 0,
    SECURE: 1,
    BOGUS: 2
};

var CertUsage = {
    CA_CERT_PIN: 0,
    EE_CERT_PIN: 1,
    CA_TA_ADDED: 2,
    EE_TA_ADDED: 3
};

var MatchingType = {
    EXACT: 0,
    SHA256: 1,
    SHA512: 2
};

var Selector = {
    FULL: 0,
    SPKI: 1
};

var DANEPolicy = {
    ALLOW_TYPE_01: 1,
    ALLOW_TYPE_23: 2
};
